final/accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path,include

app_name = "accounts"

urlpatterns = [
    url(r"^register/$", views.register, name = "signup"),
    url(r"^register2/$", views.register2, name = "signup2"),
    url(r"^login/$", views.sign_in, name = "signin"),
    url(r"^logout/$", views.logout_view, name = "logout"),
    url(r"^services/$", views.services, name = "services"),
    url(r"^aboutus/$", views.aboutus, name = "aboutus"),
    url(r"^contactus/$", views.contactus, name = "contactus"),
    path('',views.homepage,name="homepage"),
]

final/bank/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from accounts import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage,name="homepage"),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^profiles/', include("profiles.urls")),
]

final/profiles/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = "profiles"

urlpatterns = [
    path(r"dashboard", views.display_menu, name="dashboard"),
    path(r"money_transfer", views.money_transfer, name='money_transfer'),
    path(r"withdraw", views.withdraw, name='withdraw'),
    path(r"deposit", views.deposit, name='deposit'),
    path(r"stat_gen", views.stat_gen, name='stat_gen'),

    path(r"redirect_from_dashboard", views.get_function_chosen,
         name="get_function_chosen"),
    path(r"account_management", views.account_management,
         name='account_management'),
    path(r"process_account_action", views.get_account_action,
         name='get_account_action'),
    path(r"get_stat_gen", views.get_transaction_action,
         name='get_transaction_action'),

]

final/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Online Bank</title>
  {% block stylecontent %}
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
  </script> {% endcomment %}
  <style>
  body{
    background-color:#D8F0F7;
  }
  </style>
</head>


<body>
  <nav style="background-color:#58B0D6;" class=" navbar navbar-expand fixed-top ">
    <div class="container ">
      <a class="navbar-brand" href="{% url 'accounts:homepage' %}"><b>C- Bank</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:homepage' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:signin' %}" id="nav-login">Login</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'accounts:signup' %}" id="nav-create">Register</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <br><br><br>


  <!-- diffrent contents rendered here-->
  {% block bodycontent %}

  <!-- FOOTER -->

  {% endblock %}
</body>

</html>

final/templates/base1.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Online Bank</title>
  {% block stylecontent %}
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
  </script> {% endcomment %}

  <style>
  body{
    background-color: #FAFCFC;
  }
  </style>
</head>
<nav style="background-color:#AAD5E3;" class=" navbar navbar-expand ">
    <div class="container ">
      <a class="navbar-brand" href="{% url 'profiles:dashboard' %}"> Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav ">
          <li class="nav-item  ">
            <a class="nav-link active" aria-current="page" href="{% url 'profiles:dashboard' %}">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:aboutus' %}" >About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:contactus' %}" >Contact Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'accounts:signin' %}" id="nav-login">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<body>
  
<br>


  <!-- diffrent contents rendered here-->
  {% block bodycontent %}

  <!-- FOOTER -->

  {% endblock %}
</body>

</html>